# 모델생성과 성능평가 Lab

In [1]:
import numpy as np 
import pandas as pd 
import os

1. customer_scaled.csv 파일을 읽어서 customer_df에 저장하시오. 저장 후에 데이터의 특성을 탐색하시오.

In [3]:
customer_df = pd.read_csv('asset/customer_scaled.csv')

2. BikeBuyer를 제외한 컬럼으로 입력변수들로, BikeBuyer를 출력변수로 하고, 훈련 데이터와 테스트 데이터를 8:2로 분할하시오.

In [4]:
customer_df

,Gender,MaritalStatus,HomeOwnerFlag,NumberCarsOwned,NumberChildrenAtHome,TotalChildren,YearlyIncome,BikeBuyer,AvgMonthSpend,Age,...,Education_Bachelors,Education_Graduate Degree,Education_High School,Education_Partial College,Education_Partial High School,Occupation_Clerical,Occupation_Management,Occupation_Manual,Occupation_Professional,Occupation_Skilled Manual
0,0.0,1.0,1.0,0.6,0.000000,0.333333,0.496842,1.0,0.324210,0.185714,...,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
1,0.0,1.0,1.0,0.4,0.333333,0.666667,0.489453,1.0,0.425201,0.400000,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0
2,1.0,0.0,0.0,0.6,0.000000,0.000000,0.536172,1.0,0.470977,0.214286,...,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
3,0.0,1.0,1.0,0.4,0.333333,0.666667,0.317083,1.0,0.605474,0.328571,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
4,0.0,0.0,1.0,0.2,0.000000,0.000000,0.231958,1.0,0.533742,0.357143,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18350,1.0,1.0,1.0,0.2,0.000000,0.666667,0.544379,0.0,0.190656,0.571429,...,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
18351,1.0,0.0,0.0,0.2,0.000000,0.000000,0.518464,1.0,0.289287,0.200000,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
18352,1.0,0.0,0.0,0.0,0.000000,0.000000,0.224543,1.0,0.257669,0.200000,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
18353,1.0,0.0,0.0,0.2,0.000000,0.000000,0.072511,0.0,0.345446,0.242857,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
18354,1.0,1.0,1.0,0.0,0.333333,0.666667,0.038028,1.0,0.385559,0.285714,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0

In [5]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(customer_df.drop('BikeBuyer', axis=1), customer_df['BikeBuyer'], test_size=0.2, random_state=121)

3. 분류 모델의 성능을 출력하는 함수 get_clf_eval()을 작성하시오.

In [11]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

def get_clf_eval(y_test, pred):
    accuracy = accuracy_score(y_test, pred)
    precision = precision_score(y_test, pred)
    recall = recall_score(y_test, pred)
    f1 = f1_score(y_test, pred)
    print('정확도: {0:.4f}, 정밀도: {1:.4f}, 재현율: {2:.4f}, F1: {3:.4f}'.format(accuracy, precision, recall, f1))

4. 의사결정나무를 만들고 분류 성능을 평가하시오.

In [12]:
# 의사결정나무 import
from sklearn.tree import DecisionTreeClassifier

# 의사결정나무 객체 생성
dt_clf = DecisionTreeClassifier()
dt_clf.fit(X_train, y_train)
dt_pred = dt_clf.predict(X_test)

get_clf_eval(y_test, dt_pred)

정확도: 0.5402, 정밀도: 0.5810, 재현율: 0.5792, F1: 0.5801

5. 로지스틱 회귀 분석 모형을 만들고 분류 성능을 평가하시오.

In [13]:
# 로지스틱 회귀 분석 모형
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression()
lr.fit(X_train, y_train)
lr_pred = lr.predict(X_test)

get_clf_eval(y_test, lr_pred)

정확도: 0.6344, 정밀도: 0.6467, 재현율: 0.7347, F1: 0.6879

6. 랜덤포레스트 모형을 만들고 분류 성능을 평가하시오.

In [14]:
# 랜덤포레스트 모형
from sklearn.ensemble import RandomForestClassifier

rf_clf = RandomForestClassifier()
rf_clf.fit(X_train, y_train)
rf_pred = rf_clf.predict(X_test)

get_clf_eval(y_test, rf_pred)

정확도: 0.6099, 정밀도: 0.6286, 재현율: 0.7054, F1: 0.6648

7. MLP 모형을 만들고 분류 성능을 평가하시오(단 히든 레이어는 (8,8)로 하시오).

In [15]:
# MLP 모형 생성
from sklearn.neural_network import MLPClassifier

mlp_clf = MLPClassifier()
mlp_clf.fit(X_train, y_train)
mlp_pred = mlp_clf.predict(X_test)

get_clf_eval(y_test, mlp_pred)

정확도: 0.6137, 정밀도: 0.6311, 재현율: 0.7114, F1: 0.6688

/Users/sohyunwoo/.pyenv/versions/data-analysis/lib/python3.11/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(